import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";

export async function GET() {
  const session = await auth();

  if (!session?.user?.id) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const user = await prisma.user.findUnique({
    where: {
      id: session.user.id,
    },
    select: {
      id: true,
      name: true,
      email: true,
      image: true,
      role: true,
      passwordHash: true,
      createdAt: true,
    },
  });

  if (!user) {
    return NextResponse.json(
      { error: "User not found" },
      { status: 404 }
    );
  }

  return NextResponse.json({
    id: user.id,
    name: user.name,
    email: user.email,
    image: user.image,
    role: user.role,
    hasPassword: Boolean(user.passwordHash),
    createdAt: user.createdAt,
  });
}

export async function PATCH(request: Request) {
  const session = await auth();

  if (!session?.user?.id) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body" },
      { status: 400 }
    );
  }

  if (!body || typeof body !== "object") {
    return NextResponse.json(
      { error: "Invalid request body" },
      { status: 400 }
    );
  }

  const data = body as {
    name?: unknown;
    image?: unknown;
  };

  /*
   * Name
   */
  let name: string | undefined;

  if (data.name !== undefined) {
    if (typeof data.name !== "string") {
      return NextResponse.json(
        { error: "Name must be a string" },
        { status: 400 }
      );
    }

    name = data.name.trim();

    if (name.length < 2) {
      return NextResponse.json(
        {
          error:
            "Name must contain at least 2 characters",
        },
        { status: 400 }
      );
    }

    if (name.length > 100) {
      return NextResponse.json(
        {
          error:
            "Name must not exceed 100 characters",
        },
        { status: 400 }
      );
    }
  }

  /*
   * Profile image
   *
   * The image URL is generated by our authenticated
   * Cloudinary upload endpoint.
   */
  let image: string | null | undefined;

  if (data.image !== undefined) {
    if (data.image === null || data.image === "") {
      image = null;
    } else if (typeof data.image === "string") {
      const imageUrl = data.image.trim();

      if (imageUrl.length > 2000) {
        return NextResponse.json(
          { error: "Image URL is too long" },
          { status: 400 }
        );
      }

      /*
       * Only allow our Cloudinary profile image URLs.
       */
      if (
        !imageUrl.startsWith(
          "https://res.cloudinary.com/"
        )
      ) {
        return NextResponse.json(
          { error: "Invalid profile image URL" },
          { status: 400 }
        );
      }

      image = imageUrl;
    } else {
      return NextResponse.json(
        { error: "Invalid image value" },
        { status: 400 }
      );
    }
  }

  if (name === undefined && image === undefined) {
    return NextResponse.json(
      { error: "No changes provided" },
      { status: 400 }
    );
  }

  const user = await prisma.user.update({
    where: {
      id: session.user.id,
    },
    data: {
      ...(name !== undefined ? { name } : {}),
      ...(image !== undefined ? { image } : {}),
    },
    select: {
      id: true,
      name: true,
      email: true,
      image: true,
      role: true,
      passwordHash: true,
    },
  });

  return NextResponse.json({
    id: user.id,
    name: user.name,
    email: user.email,
    image: user.image,
    role: user.role,
    hasPassword: Boolean(user.passwordHash),
  });
}