"use client";

type ContentBlock =
  | {
      type: "text";
      text: string;
    }
  | {
      type: "image";
      url: string;
    };

type ArticleContentProps = {
  content: string;
};

/* =====================================================
   CONTENT BLOCK VALIDATION
===================================================== */

function isContentBlockArray(
  value: unknown
): value is ContentBlock[] {
  if (!Array.isArray(value)) {
    return false;
  }

  return value.every((block) => {
    if (!block || typeof block !== "object") {
      return false;
    }

    const item = block as Record<string, unknown>;

    if (item.type === "text") {
      return typeof item.text === "string";
    }

    if (item.type === "image") {
      return typeof item.url === "string";
    }

    return false;
  });
}

/* =====================================================
   HTML SANITIZER
===================================================== */

/*
 * The admin editor only needs a controlled set of HTML
 * elements. We allow formatting generated by the editor
 * and remove everything else.
 */
function sanitizeArticleHtml(
  html: string
) {
  let safe = html;

  /* ---------------------------------------------
     Remove dangerous elements completely
  --------------------------------------------- */

  safe = safe.replace(
    /<\s*(script|iframe|object|embed|form|style|link|meta|base|svg|math)[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi,
    ""
  );

  safe = safe.replace(
    /<\s*(script|iframe|object|embed|form|style|link|meta|base|svg|math)[^>]*\/?\s*>/gi,
    ""
  );

  /* ---------------------------------------------
     Remove inline event handlers
     onclick=""
     onload=""
     onerror=""
     etc.
  --------------------------------------------- */

  safe = safe.replace(
    /\s+on[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,
    ""
  );

  /* ---------------------------------------------
     Remove javascript: URLs
  --------------------------------------------- */

  safe = safe.replace(
    /\s+(href|src)\s*=\s*(?:"[^"]*javascript:[^"]*"|'[^']*javascript:[^']*')/gi,
    ""
  );

  /* ---------------------------------------------
     Remove style attributes.

     The editor does not need inline styles.
  --------------------------------------------- */

  safe = safe.replace(
    /\s+style\s*=\s*(?:"[^"]*"|'[^']*')/gi,
    ""
  );

  /* ---------------------------------------------
     Keep only the HTML tags supported by the
     article editor.
  --------------------------------------------- */

  safe = safe.replace(
    /<\/?([a-z0-9-]+)(?:\s[^>]*)?>/gi,
    (match, tag: string) => {
      const allowedTags = [
        "p",
        "br",
        "strong",
        "b",
        "em",
        "i",
        "u",
        "h1",
        "h2",
        "h3",
        "ul",
        "ol",
        "li",
      ];

      if (
        allowedTags.includes(
          tag.toLowerCase()
        )
      ) {
        /*
         * Remove attributes from allowed tags.
         * Article formatting doesn't require them.
         */
        const isClosingTag =
          /^<\s*\//.test(match);

        if (isClosingTag) {
          return `</${tag.toLowerCase()}>`;
        }

        if (
          tag.toLowerCase() === "br"
        ) {
          return "<br />";
        }

        return `<${tag.toLowerCase()}>`;
      }

      return "";
    }
  );

  return safe;
}

/* =====================================================
   CHECK WHETHER CONTENT CONTAINS HTML
===================================================== */

function containsArticleHtml(
  text: string
) {
  return /<\s*(p|br|strong|b|em|i|u|h1|h2|h3|ul|ol|li)\b/i.test(
    text
  );
}

/* =====================================================
   LEGACY TEXT RENDERER
===================================================== */

/*
 * Keeps support for older articles that were written
 * using plain text and Markdown-style headings.
 */
function renderPlainText(
  text: string
) {
  const lines = text.split("\n");

  return lines.map(
    (line, index) => {
      const trimmed =
        line.trim();

      if (!trimmed) {
        return (
          <div
            key={index}
            className="h-4"
          />
        );
      }

      /*
       * H3 must be checked before H2/H1-style
       * fallback handling.
       */
      if (
        trimmed.startsWith(
          "### "
        )
      ) {
        return (
          <h3
            key={index}
            className="mb-4 mt-8 text-xl font-semibold leading-tight tracking-tight text-gray-900 dark:text-white"
          >
            {trimmed.replace(
              /^###\s+/,
              ""
            )}
          </h3>
        );
      }

      if (
        trimmed.startsWith(
          "## "
        )
      ) {
        return (
          <h2
            key={index}
            className="mb-5 mt-10 text-2xl font-bold leading-tight tracking-tight text-gray-900 dark:text-white"
          >
            {trimmed.replace(
              /^##\s+/,
              ""
            )}
          </h2>
        );
      }

      return (
        <p
          key={index}
          className="mb-5 text-[17px] leading-8 text-gray-700 dark:text-white/80"
        >
          {trimmed}
        </p>
      );
    }
  );
}

/* =====================================================
   HTML TEXT BLOCK
===================================================== */

function renderHtmlText(
  text: string
) {
  const safeHtml =
    sanitizeArticleHtml(text);

  return (
    <div
      className="
        article-rich-content
        text-[17px]
        leading-8
        text-gray-700
        dark:text-white/80

        [&_p]:mb-5
        [&_p]:leading-8

        [&_h1]:mb-5
        [&_h1]:mt-10
        [&_h1]:text-3xl
        [&_h1]:font-bold
        [&_h1]:leading-tight
        [&_h1]:tracking-tight
        [&_h1]:text-gray-900
        dark:[&_h1]:text-white

        [&_h2]:mb-4
        [&_h2]:mt-10
        [&_h2]:text-2xl
        [&_h2]:font-bold
        [&_h2]:leading-tight
        [&_h2]:tracking-tight
        [&_h2]:text-gray-900
        dark:[&_h2]:text-white

        [&_h3]:mb-3
        [&_h3]:mt-8
        [&_h3]:text-xl
        [&_h3]:font-semibold
        [&_h3]:leading-tight
        [&_h3]:tracking-tight
        [&_h3]:text-gray-900
        dark:[&_h3]:text-white

        [&_strong]:font-bold
        [&_b]:font-bold

        [&_em]:italic
        [&_i]:italic

        [&_u]:underline
        [&_u]:decoration-1
        [&_u]:underline-offset-2

        [&_ul]:mb-6
        [&_ul]:list-disc
        [&_ul]:space-y-2
        [&_ul]:pl-7

        [&_ol]:mb-6
        [&_ol]:list-decimal
        [&_ol]:space-y-2
        [&_ol]:pl-7

        [&_li]:leading-8

        [&_br]:leading-8
      "
      dangerouslySetInnerHTML={{
        __html: safeHtml,
      }}
    />
  );
}

/* =====================================================
   TEXT BLOCK RENDERER
===================================================== */

function renderText(
  text: string
) {
  /*
   * New rich-text editor content contains HTML.
   *
   * Old content contains plain text / Markdown-style
   * headings.
   */
  if (
    containsArticleHtml(text)
  ) {
    return renderHtmlText(
      text
    );
  }

  return renderPlainText(
    text
  );
}

/* =====================================================
   ZERO TRACE WATERMARK
===================================================== */

function Watermark() {
  return (
    <div
      className="pointer-events-none absolute inset-0 z-0 flex justify-center"
      aria-hidden="true"
    >
      <div
        className="sticky top-32 h-[280px] w-[280px] bg-contain bg-center bg-no-repeat opacity-[0.035] dark:opacity-[0.08]"
        style={{
          backgroundImage:
            "url('/branding/zerotrace-watermark.png')",
        }}
      />
    </div>
  );
}

/* =====================================================
   ARTICLE CONTENT
===================================================== */

export default function ArticleContent({
  content,
}: ArticleContentProps) {
  let parsedContent: unknown =
    null;

  try {
    parsedContent =
      JSON.parse(content);
  } catch {
    parsedContent = null;
  }

  /* ===================================================
     NEW CONTENT BLOCK FORMAT
  =================================================== */

  if (
    isContentBlockArray(
      parsedContent
    )
  ) {
    return (
      <div className="relative">
        {/* =================================================
            ZERO TRACE WATERMARK
        ================================================= */}

        <Watermark />

        {/* =================================================
            ARTICLE CONTENT
        ================================================= */}

        <div className="relative z-10">
          {parsedContent.map(
            (block, index) => {
              /* -------------------------------------------
                 TEXT BLOCK
              ------------------------------------------- */

              if (
                block.type ===
                "text"
              ) {
                return (
                  <div
                    key={`text-${index}`}
                  >
                    {renderText(
                      block.text
                    )}
                  </div>
                );
              }

              /* -------------------------------------------
                 IMAGE BLOCK
              ------------------------------------------- */

              return (
                <figure
                  key={`image-${index}`}
                  className="my-12 flex justify-center"
                >
                  <div className="w-full max-w-3xl overflow-hidden rounded-xl border border-gray-200 bg-gray-50 p-2 shadow-sm dark:border-white/10 dark:bg-white/[0.025] dark:shadow-black/10 sm:p-3">
                    <img
                      src={block.url}
                      alt="CyberIncidents article image"
                      className="mx-auto max-h-[500px] w-auto max-w-full rounded-lg object-contain"
                      loading="lazy"
                      decoding="async"
                    />
                  </div>
                </figure>
              );
            }
          )}
        </div>
      </div>
    );
  }

  /* ===================================================
     LEGACY PLAIN TEXT CONTENT
  =================================================== */

  return (
    <div className="relative">
      {/* =================================================
          ZERO TRACE WATERMARK
      ================================================= */}

      <Watermark />

      {/* =================================================
          ARTICLE CONTENT
      ================================================= */}

      <div className="relative z-10">
        {renderText(content)}
      </div>
    </div>
  );
}